#!/bin/bash
# Create an alphabetical symbol table in sympico.i for inclusion in
# sympico.c as called by sysadr in bbccon.c.  To add more symbols
# to the table place them anywhere in the input to sort.  Then add
# the relevant include files to sympico.c
{
	sort <<END
gpio_set_function 
gpio_set_pulls 
gpio_pull_up 
gpio_is_pulled_up 
gpio_pull_down 
gpio_is_pulled_down 
gpio_disable_pulls 
gpio_set_irqover 
gpio_set_outover 
gpio_set_inover 
gpio_set_oeover 
gpio_set_input_enabled 
gpio_set_input_hysteresis_enabled 
gpio_is_input_hysteresis_enabled 
gpio_set_slew_rate 
gpio_get_slew_rate 
gpio_set_drive_strength 
gpio_get_drive_strength 
gpio_set_irq_enabled 
gpio_set_irq_enabled_with_callback 
gpio_set_dormant_irq_enabled 
gpio_acknowledge_irq 
gpio_init 
gpio_init_mask 
gpio_get 
gpio_get_all 
gpio_set_mask 
gpio_clr_mask 
gpio_xor_mask 
gpio_put_masked 
gpio_put_all 
gpio_put 
gpio_get_out_level 
gpio_set_dir_out_masked 
gpio_set_dir_in_masked 
gpio_set_dir_masked 
gpio_set_dir_all_bits 
gpio_set_dir 
gpio_is_dir_out 
gpio_get_dir 
memmove
memcpy
memset
memcmp
memchr
END
} | {
	printf "// sympico.i -- Alphabetical list of SDK function calls\n"
	printf "// Automatically generated by sympico.sh -- DO NOT EDIT\n"
	first=true
	while read i
	do
case $first in
false)
		printf ",\n"
esac
		first=false
		printf "SYMADD(%s)" "$i"
	done
	printf "\n"
} > sympico.i
